import React,{useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{Building2,ClipboardList,FileCheck2,Euro,AlertTriangle,Camera,Cloud,BarChart3,BookOpen,Bot,Save,PlusCircle,MapPin,Download,RefreshCw,Trash2,Wand2,Search,Upload,CalendarDays}from'lucide-react'
import jsPDF from'jspdf'
import'./style.css'

const STORE='rjp_obras_melhorada_v31'
const seedR=[
{id:'ECA-COB-001',fonte:'ECAACR/RJP',cat:'Reabilitação',dom:'Coberturas',desc:'Substituição de cobertura em telha cerâmica',un:'m²',mo:.75,prod:25,mat:'Telha; ripado; acessórios',eq:'Andaime; ferramentas',pu:42},
{id:'ECA-FAC-001',fonte:'ECAACR/RJP',cat:'Reabilitação',dom:'Fachadas',desc:'Reparação e pintura de fachada',un:'m²',mo:.55,prod:35,mat:'Argamassa; primário; tinta',eq:'Andaime; lavadora',pu:28},
{id:'ECA-DEM-001',fonte:'ECAACR/RJP',cat:'Demolições',dom:'Demolições',desc:'Demolição manual de alvenaria',un:'m²',mo:.65,prod:18,mat:'-',eq:'Martelo elétrico; contentor',pu:22},
{id:'FER-VED-001',fonte:'RJP Ferrovia',cat:'Ferrovia',dom:'Vedações',desc:'Execução/substituição de vedação metálica',un:'m',mo:.40,prod:60,mat:'Postes; rede; fixações',eq:'Berbequim; viatura',pu:35},
{id:'FER-DRE-001',fonte:'RJP Ferrovia',cat:'Ferrovia',dom:'Drenagem',desc:'Limpeza/reperfilamento de valeta',un:'m',mo:.18,prod:120,mat:'-',eq:'Mini-escavadora; viatura',pu:9},
{id:'FER-AMV-001',fonte:'RJP Ferrovia',cat:'Ferrovia',dom:'AMV',desc:'Inspeção funcional de AMV e MPS',un:'un',mo:2.5,prod:4,mat:'Lubrificante; consumíveis',eq:'Ferramentas de via',pu:180},
{id:'EDF-PIN-001',fonte:'RJP Edifícios',cat:'Edificação',dom:'Pinturas',desc:'Pintura interior de paredes',un:'m²',mo:.20,prod:90,mat:'Primário; tinta plástica',eq:'Rolo; trincha',pu:8}
]
const seedO=[{id:'obra-demo',nome:'Exemplo - Reabilitação de Edifício Ferroviário',cliente:'Infraestruturas de Portugal',empreiteiro:'Empreiteiro Exemplo',fiscalizacao:'RJP',local:'Linha do Oeste',gps:'',inicio:'2026-06-01',fim:'2026-08-30',valor:85000,estado:'Em curso',progresso:35,contrato:'CT-2026-001',obs:'Obra de demonstração.'}]
const empty={obra:{nome:'',cliente:'',empreiteiro:'',fiscalizacao:'',local:'',gps:'',inicio:'',fim:'',valor:'',estado:'Em preparação',progresso:0,contrato:'',obs:''},dia:{obraId:'',data:new Date().toISOString().slice(0,10),meteo:'',equipa:'',trab:'',ocor:'',gps:'',ia:''},ren:{fonte:'RJP',cat:'Edificação',dom:'',desc:'',un:'m²',mo:'',prod:'',mat:'',eq:'',pu:''},cus:{obraId:'',data:new Date().toISOString().slice(0,10),rid:'',desc:'',qtd:'',prev:'',real:'',auto:'',tipo:'Custo'},lic:{obraId:'',tipo:'Licença de obra',entidade:'',num:'',emissao:'',validade:'',estado:'Válida',link:'',obs:''},nc:{obraId:'',data:new Date().toISOString().slice(0,10),local:'',desc:'',grav:'Média',resp:'',prazo:'',estado:'Aberta',gps:''},foto:{obraId:'',data:new Date().toISOString().slice(0,10),titulo:'',cat:'Obra',gps:'',desc:'',ficheiro:'',ia:''}}
function uid(p){return p+'_'+Math.random().toString(36).slice(2,8)+'_'+Date.now().toString(36).slice(-5)}
function def(){return{obras:seedO,diarios:[],licencas:[],ncs:[],custos:[],fotos:[],rend:seedR,settings:{url:''}}}
function load(){try{return{...def(),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return def()}}
function App(){
const[data,setData]=useState(load()),[tab,setTab]=useState('dash'),[q,setQ]=useState(''),[obra,setObra]=useState(empty.obra),[dia,setDia]=useState(empty.dia),[ren,setRen]=useState(empty.ren),[cus,setCus]=useState(empty.cus),[lic,setLic]=useState(empty.lic),[nc,setNc]=useState(empty.nc),[foto,setFoto]=useState(empty.foto),[ai,setAi]=useState('')
const persist=n=>{setData(n);localStorage.setItem(STORE,JSON.stringify(n))}
const obraName=id=>data.obras.find(o=>o.id===id)?.nome||'Sem obra'
const prev=data.custos.reduce((s,c)=>s+(+c.prev||0),0), real=data.custos.reduce((s,c)=>s+(+c.real||0),0)
const prog=data.obras.length?Math.round(data.obras.reduce((s,o)=>s+(+o.progresso||0),0)/data.obras.length):0
const lic30=data.licencas.filter(l=>l.validade&&((new Date(l.validade)-new Date())/864e5)<=30&&((new Date(l.validade)-new Date())/864e5)>=0).length
const nca=data.ncs.filter(n=>n.estado!=='Fechada').length
const atrasos=data.obras.filter(o=>o.fim&&new Date(o.fim)<new Date()&&o.estado!=='Concluída'&&o.estado!=='Encerrada').length
const tabs=[['dash','Dashboard',BarChart3],['obras','Obras',Building2],['diario','Diário IA',ClipboardList],['rend','Rendimentos',BookOpen],['custos','Custos/Autos',Euro],['lic','Licenças',FileCheck2],['nc','NC',AlertTriangle],['fotos','Fotos GPS',Camera],['google','Google',Cloud],['ia','Assistente IA',Bot]]
function add(k,obj,setter,emp,p){persist({...data,[k]:[{...obj,id:uid(p)},...data[k]]});setter(emp)}
function del(k,id){persist({...data,[k]:data[k].filter(x=>x.id!==id)})}
function gps(setter,obj){if(!navigator.geolocation){alert('GPS não disponível');return}navigator.geolocation.getCurrentPosition(p=>setter({...obj,gps:`${p.coords.latitude.toFixed(7)}, ${p.coords.longitude.toFixed(7)}`}),()=>alert('Sem GPS'),{enableHighAccuracy:true,timeout:15000})}
function pdf(){const d=new jsPDF();let y=18;d.setFontSize(18);d.text('RJP Obras - Relatório Geral',14,y);y+=10;d.setFontSize(10);[`Obras: ${data.obras.length}`,`Progresso médio: ${prog}%`,`Custos previstos: ${prev.toFixed(2)} EUR`,`Custos reais: ${real.toFixed(2)} EUR`,`Licenças a vencer: ${lic30}`,`NC abertas: ${nca}`].forEach(l=>{d.text(l,14,y);y+=7});y+=6;d.setFontSize(13);d.text('Obras',14,y);y+=8;d.setFontSize(9);data.obras.forEach(o=>{if(y>280){d.addPage();y=18}d.text(`• ${o.nome} | ${o.local} | ${o.estado} | ${o.progresso}%`,14,y);y+=6});d.save('RJP_Obras_Relatorio.pdf')}
function exportJson(){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='RJP_Obras_backup.json';a.click()}
function importJson(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{persist({...def(),...JSON.parse(r.result)});alert('Importado')}catch{alert('Ficheiro inválido')}};r.readAsText(f)}
function diaIA(){const t=(dia.trab+' '+dia.ocor).toLowerCase();let r='Resumo IA: '; if(t.includes('ved')||t.includes('rede'))r+='atividade de vedações; '; if(t.includes('cob')||t.includes('telha'))r+='atividade de cobertura; '; if(t.includes('hum')||t.includes('infil'))r+='possível humidade/infiltração; '; if(t.includes('atras'))r+='risco de atraso; '; if(r==='Resumo IA: ')r+='sem alertas automáticos.'; setDia({...dia,ia:r})}
function calcCusto(){const r=data.rend.find(x=>x.id===cus.rid);if(!r){alert('Seleciona rendimento');return}const qtd=+cus.qtd||0;setCus({...cus,desc:r.desc,prev:(qtd*(+r.pu||0)).toFixed(2)})}
function assist(){const t=ai.toLowerCase(),m=t.match(/(\d+[\.,]?\d*)\s*(m2|m²|m|ml|un)/),qtd=m?+m[1].replace(',','.'):0;let r=null;if(t.includes('ved'))r=data.rend.find(x=>x.dom==='Vedações');if(t.includes('cob'))r=data.rend.find(x=>x.dom==='Coberturas');if(t.includes('fach'))r=data.rend.find(x=>x.dom==='Fachadas');if(t.includes('dren'))r=data.rend.find(x=>x.dom==='Drenagem');if(r&&qtd){setAi(`Sugestão IA RJP Obras:\nAtividade: ${r.desc}\nQuantidade: ${qtd} ${r.un}\nDuração: ${Math.ceil(qtd/(+r.prod||1))} dias/equipa\nCusto: ${(qtd*(+r.pu||0)).toFixed(2)} EUR\nMão-de-obra: ${(qtd*(+r.mo||0)).toFixed(2)} h`)}else setAi('Escreve por exemplo: executar 120 m de vedação; substituir 850 m² de cobertura.')}
async function sync(){try{if(!data.settings.url)throw Error('URL vazio');await fetch(data.settings.url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify({app:'RJP Obras',payload:data})});alert('Sincronização enviada')}catch(e){alert(e.message)}}
const filtered=arr=>arr.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()))
return <div className="app"><aside><div className="brand"><div className="logo">RJP</div><div><h1>RJP Obras</h1><p>V3.1 · APK + WebApp</p></div></div><nav>{tabs.map(([id,l,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I size={18}/>{l}</button>)}</nav><button className="sideDanger" onClick={()=>confirm('Repor dados?')&&persist(def())}><Trash2 size={16}/>Repor dados</button></aside><main><header className="top"><div><h2>{tabs.find(t=>t[0]===tab)?.[1]}</h2><p>Gestão de obra, rendimentos, autos, licenças, GPS, Google e PDF.</p></div><div className="actions"><button onClick={pdf}><Download size={16}/>PDF</button><button onClick={exportJson}><Download size={16}/>Backup</button><label className="upload"><Upload size={16}/>Importar<input type="file" accept="application/json" onChange={importJson}/></label></div></header><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar em todos os registos..."/></div>
{tab==='dash'&&<><div className="cards"><Card t="Obras" v={data.obras.length}/><Card t="Progresso" v={prog+'%'}/><Card t="Em atraso" v={atrasos} warn={atrasos}/><Card t="Licenças 30 dias" v={lic30} warn={lic30}/><Card t="NC abertas" v={nca} warn={nca}/><Card t="Previsto/Real" v={`${prev.toFixed(0)}€ / ${real.toFixed(0)}€`}/></div><Panel title="Curva S simplificada"><div className="curve"><div style={{width:Math.min(prog,100)+'%'}}>{prog}%</div></div></Panel><Panel title="Últimas obras"><List items={filtered(data.obras).slice(0,8)} render={o=><><b>{o.nome}</b><span>{o.local} · {o.estado} · {o.progresso}%</span></>}/></Panel></>}
{tab==='obras'&&<Crud title="Cadastro de obra" obj={obra} set={setObra} fields={[['Nome','nome'],['Cliente','cliente'],['Empreiteiro','empreiteiro'],['Fiscalização','fiscalizacao'],['Contrato','contrato'],['Local','local'],['GPS','gps'],['Início','inicio','date'],['Fim','fim','date'],['Valor','valor','number'],['Progresso','progresso','number']]} extra={<><Select label="Estado" v={obra.estado} set={v=>setObra({...obra,estado:v})} opts={['Em preparação','Em curso','Suspensa','Concluída','Encerrada']}/><TA label="Observações" v={obra.obs} set={v=>setObra({...obra,obs:v})}/></>} actions={<><button onClick={()=>gps(setObra,obra)}><MapPin size={16}/>GPS</button><button className="primary" onClick={()=>add('obras',obra,setObra,empty.obra,'obra')}><PlusCircle size={16}/>Guardar</button></>}/>} list={<Panel title="Obras registadas"><List items={filtered(data.obras)} onDelete={id=>del('obras',id)} render={o=><><b>{o.nome}</b><span>{o.cliente} · {o.local} · {o.estado}</span></>}/></Panel>}/>}
{tab==='diario'&&<><Panel title="Diário de obra com IA"><div className="grid"><SelObra data={data} v={dia.obraId} set={v=>setDia({...dia,obraId:v})}/><F label="Data" type="date" v={dia.data} set={v=>setDia({...dia,data:v})}/><F label="Meteorologia" v={dia.meteo} set={v=>setDia({...dia,meteo:v})}/><F label="Equipas" v={dia.equipa} set={v=>setDia({...dia,equipa:v})}/><F label="GPS" v={dia.gps} set={v=>setDia({...dia,gps:v})}/><TA label="Trabalhos" v={dia.trab} set={v=>setDia({...dia,trab:v})}/><TA label="Ocorrências" v={dia.ocor} set={v=>setDia({...dia,ocor:v})}/><TA label="Resumo IA" v={dia.ia} set={v=>setDia({...dia,ia:v})}/></div><div className="row"><button onClick={()=>gps(setDia,dia)}><MapPin size={16}/>GPS</button><button onClick={diaIA}><Wand2 size={16}/>Analisar</button><button className="primary" onClick={()=>add('diarios',dia,setDia,empty.dia,'dia')}><Save size={16}/>Guardar</button></div></Panel><Panel title="Diários"><List items={filtered(data.diarios)} onDelete={id=>del('diarios',id)} render={d=><><b>{d.data} · {obraName(d.obraId)}</b><span>{d.trab}</span><small>{d.ia}</small></>}/></Panel></>}
{tab==='rend'&&<><Panel title="Biblioteca de rendimentos"><div className="grid"><Select label="Fonte" v={ren.fonte} set={v=>setRen({...ren,fonte:v})} opts={['RJP','LNEC/Paz Branco','ECAACR','RJP Ferrovia']}/><Select label="Categoria" v={ren.cat} set={v=>setRen({...ren,cat:v})} opts={['Edificação','Reabilitação','Ferrovia','Demolições','Ensaios']}/><F label="Domínio" v={ren.dom} set={v=>setRen({...ren,dom:v})}/><F label="Descrição" v={ren.desc} set={v=>setRen({...ren,desc:v})}/><F label="Unidade" v={ren.un} set={v=>setRen({...ren,un:v})}/><F label="MO h/un" type="number" v={ren.mo} set={v=>setRen({...ren,mo:v})}/><F label="Produção dia" type="number" v={ren.prod} set={v=>setRen({...ren,prod:v})}/><F label="Preço unitário" type="number" v={ren.pu} set={v=>setRen({...ren,pu:v})}/><TA label="Materiais" v={ren.mat} set={v=>setRen({...ren,mat:v})}/><TA label="Equipamento" v={ren.eq} set={v=>setRen({...ren,eq:v})}/></div><button className="primary" onClick={()=>add('rend',ren,setRen,empty.ren,'rend')}><PlusCircle size={16}/>Adicionar</button></Panel><Panel title="Base técnica"><List items={filtered(data.rend)} onDelete={id=>del('rend',id)} render={r=><><b>{r.id} · {r.desc}</b><span>{r.fonte} · {r.dom} · {r.un} · {r.pu}€/un · {r.prod} un/dia</span></>}/></Panel></>}
{tab==='custos'&&<><Panel title="Custos e autos"><div className="grid"><SelObra data={data} v={cus.obraId} set={v=>setCus({...cus,obraId:v})}/><F label="Data" type="date" v={cus.data} set={v=>setCus({...cus,data:v})}/><label className="field"><span>Atividade</span><select value={cus.rid} onChange={e=>setCus({...cus,rid:e.target.value})}><option value="">Selecionar</option>{data.rend.map(r=><option key={r.id} value={r.id}>{r.id} · {r.desc}</option>)}</select></label><Select label="Tipo" v={cus.tipo} set={v=>setCus({...cus,tipo:v})} opts={['Custo','Auto de medição','Trabalho a mais','Trabalho a menos']}/><F label="Quantidade" type="number" v={cus.qtd} set={v=>setCus({...cus,qtd:v})}/><F label="Previsto" type="number" v={cus.prev} set={v=>setCus({...cus,prev:v})}/><F label="Real" type="number" v={cus.real} set={v=>setCus({...cus,real:v})}/><F label="Auto nº" v={cus.auto} set={v=>setCus({...cus,auto:v})}/><TA label="Descrição" v={cus.desc} set={v=>setCus({...cus,desc:v})}/></div><div className="row"><button onClick={calcCusto}><Wand2 size={16}/>Calcular</button><button className="primary" onClick={()=>add('custos',cus,setCus,empty.cus,'cus')}><Save size={16}/>Guardar</button></div></Panel><Panel title="Custos/autos"><List items={filtered(data.custos)} onDelete={id=>del('custos',id)} render={c=><><b>{c.tipo} · {obraName(c.obraId)}</b><span>{c.desc} · Qtd {c.qtd||'-'} · Prev. {c.prev||0}€ · Real {c.real||0}€</span></>}/></Panel></>}
{tab==='lic'&&<><SimpleForm title="Licenças" obj={lic} set={setLic} fields={[['Tipo','tipo'],['Entidade','entidade'],['Número','num'],['Emissão','emissao','date'],['Validade','validade','date'],['Estado','estado'],['Link','link']]} before={<SelObra data={data} v={lic.obraId} set={v=>setLic({...lic,obraId:v})}/>} ta={['Observações','obs']} save={()=>add('licencas',lic,setLic,empty.lic,'lic')}/><Panel title="Licenças"><List items={filtered(data.licencas)} onDelete={id=>del('licencas',id)} render={l=><><b>{l.tipo} · {obraName(l.obraId)}</b><span>{l.estado} · validade: {l.validade||'-'}</span></>}/></Panel></>}
{tab==='nc'&&<><SimpleForm title="Não conformidades" obj={nc} set={setNc} fields={[['Data','data','date'],['Local','local'],['Gravidade','grav'],['Responsável','resp'],['Prazo','prazo','date'],['Estado','estado'],['GPS','gps']]} before={<SelObra data={data} v={nc.obraId} set={v=>setNc({...nc,obraId:v})}/>} ta={['Descrição','desc']} save={()=>add('ncs',nc,setNc,empty.nc,'nc')} more={<button onClick={()=>gps(setNc,nc)}><MapPin size={16}/>GPS</button>}/><Panel title="NC registadas"><List items={filtered(data.ncs)} onDelete={id=>del('ncs',id)} render={n=><><b>{n.grav} · {obraName(n.obraId)}</b><span>{n.desc} · {n.estado} · prazo {n.prazo||'-'}</span></>}/></Panel></>}
{tab==='fotos'&&<><SimpleForm title="Fotografias GPS" obj={foto} set={setFoto} fields={[['Data','data','date'],['Título','titulo'],['Categoria','cat'],['GPS','gps'],['Ficheiro/Link','ficheiro']]} before={<SelObra data={data} v={foto.obraId} set={v=>setFoto({...foto,obraId:v})}/>} ta={['Descrição','desc']} save={()=>add('fotos',foto,setFoto,empty.foto,'foto')} more={<><button onClick={()=>gps(setFoto,foto)}><MapPin size={16}/>GPS</button><button onClick={()=>setFoto({...foto,ia:'Análise IA: verificar fissuras, corrosão, humidades e segurança.'})}><Wand2 size={16}/>IA</button></>}/><Panel title="Fotos"><List items={filtered(data.fotos)} onDelete={id=>del('fotos',id)} render={f=><><b>{f.titulo||f.cat} · {obraName(f.obraId)}</b><span>{f.data} · {f.gps}</span><small>{f.ia}</small></>}/></Panel></>}
{tab==='google'&&<Panel title="Google Drive / Sheets"><p className="muted">Cola o URL /exec do Apps Script. A app envia a base e o script cria folhas e pastas por obra.</p><F label="URL Apps Script" v={data.settings.url} set={v=>persist({...data,settings:{...data.settings,url:v}})}/><button className="primary" onClick={sync}><RefreshCw size={16}/>Sincronizar</button></Panel>}
{tab==='ia'&&<Panel title="Assistente IA de obra"><TA label="Pedido" v={ai} set={setAi}/><button className="primary" onClick={assist}><Bot size={16}/>Calcular sugestão</button><p className="muted">Exemplo: executar 120 m de vedação; substituir 850 m² de cobertura.</p></Panel>}
</main></div>}
function F({label,v,set,type='text'}){return <label className="field"><span>{label}</span><input type={type} value={v||''} onChange={e=>set(e.target.value)}/></label>}
function TA({label,v,set}){return <label className="field wide"><span>{label}</span><textarea value={v||''} onChange={e=>set(e.target.value)}/></label>}
function Select({label,v,set,opts}){return <label className="field"><span>{label}</span><select value={v||''} onChange={e=>set(e.target.value)}>{opts.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
function SelObra({data,v,set}){return <label className="field"><span>Obra</span><select value={v||''} onChange={e=>set(e.target.value)}><option value="">Selecionar obra</option>{data.obras.map(o=><option key={o.id} value={o.id}>{o.nome}</option>)}</select></label>}
function Card({t,v,warn}){return <div className={warn?'card warning':'card'}><span>{t}</span><strong>{v}</strong></div>}
function Panel({title,children}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function List({items,render,onDelete}){if(!items.length)return <p className="muted">Ainda sem registos.</p>;return <div className="list">{items.map(i=><div className="listItem" key={i.id}><div>{render(i)}</div>{onDelete&&<button className="icon danger" onClick={()=>onDelete(i.id)}><Trash2 size={16}/></button>}</div>)}</div>}
function Crud({title,obj,set,fields,extra,actions,list}){return <><Panel title={title}><div className="grid">{fields.map(([l,k,t])=><F key={k} label={l} type={t||'text'} v={obj[k]} set={v=>set({...obj,[k]:v})}/>)}{extra}</div><div className="row">{actions}</div></Panel>{list}</>}
function SimpleForm({title,obj,set,fields,before,ta,save,more}){return <Panel title={title}><div className="grid">{before}{fields.map(([l,k,t])=><F key={k} label={l} type={t||'text'} v={obj[k]} set={v=>set({...obj,[k]:v})}/>)}{ta&&<TA label={ta[0]} v={obj[ta[1]]} set={v=>set({...obj,[ta[1]]:v})}/>}</div><div className="row">{more}<button className="primary" onClick={save}><Save size={16}/>Guardar</button></div></Panel>}
createRoot(document.getElementById('root')).render(<App/>)
